### ISSUE TITLE
"/usr/bin/env: node --harmony: No such file or directory" error on Ubuntu 15.10

### ISSUE THREAD

**Issue by adjioev** [SpencerCDixon/redux-cli#42] opened 2016-03-04 07:15 UTC
Hi,

I've installed redux-cli with: 
`sudo npm -g install redux-cli
`
And I get the following error: 
`/usr/bin/env: node --harmony: No such file or directory

Env:

```
:~/sandbox$ node -v
v5.7.0
:~/sandbox$ npm -v
3.6.0
```

Looks like there is a problem with bang sign, here is a link with similar error:
https://github.com/azproduction/node-mc/issues/3

Thanks Alex
`

**Comment by yedlosh** [comment] 2016-03-04 16:09
I have the same problem. 

Env: same node and npm as OP, Ubuntu 14.04 LTS.

**Comment by SpencerCDixon** [comment] 2016-03-04 20:33
Will try to get to it over the weekend

**Comment by SpencerCDixon** [comment] 2016-03-05 18:32
[See here for potential solution](https://github.com/SpencerCDixon/redux-cli/issues/39)

**Comment by yedlosh** [comment] 2016-03-05 22:18
As pointed out in https://github.com/SpencerCDixon/redux-cli/issues/39 the problem is that Linux kernel does not support multiple arguments in shebangs, so you can't pass the --harmony flag using
`#!/usr/bin/env node --harmony`

Solution to this problem is to not use env but directly call 
`#!/usr/bin/node --harmony`

**Comment by yedlosh** [comment] 2016-03-05 22:24
Also found this hack for passing arguments to shebang
http://sambal.org/2014/02/passing-options-node-shebang-line/

**Comment by yedlosh** [comment] 2016-03-05 22:53
There is a question though, if you should even bother to use `--harmony` flag, as most of the ES6 features are already active in Node without need for any flags. 

The only features `--harmony` activates are now: 
Symbol.toStringTag, Array.prototype.includes and Rest Parameters ([see here](https://nodejs.org/en/docs/es6/))

**Comment by anithri** [comment] 2017-09-18 19:39
I'm not familiar enough with node to understand all of the nuances of this.  I"m running fine on Ubuntu 16.04 with just `#!/usr/bin/env node`

I'm closing this for now.

**Closed by anithri** 2017-09-18 19:39 UTC
Labels: bug
